### ISSUE TITLE
Error running test script

### ISSUE THREAD

**Issue by anaelleltd** [James-Sangalli/balances-rpc-dot#2]
Not sure what is missing, but I got: 

_λ npm run test

> balances-rpc-dot@1.0.0 test C:\Users\atale\Documents\Gits\balances-rpc-dot
> mocha --exit --recursive

'mocha' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! balances-rpc-dot@1.0.0 test: `mocha --exit --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the balances-rpc-dot@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\atale\AppData\Roaming\npm-cache\_logs\2021-08-19T05_11_28_127Z-debug.log_

**Comment by JamesANZ** [comment]
Hi @anaelleltd, sorry about that. I had installed mocha globally and therefore oversaw this.

I have added mocha in as a dev dependency here: https://github.com/James-Sangalli/balances-rpc-dot/commit/0ae642b656c00a1643b2237839318990b6469807

Please pull, `npm i` and re run

**Comment by anaelleltd** [comment]
Thanks for that.
Now, I am getting the message below, but no balance object. 
I don't see any explicit endpoint in the code. Is this an issue?

_λ npm run test

> balances-rpc-dot@1.0.0 test C:\Users\atale\Documents\Gits\balances-rpc-dot
> mocha --exit --recursive

  AccountInfo functionality
    √ should be able to get a native balances object (1492ms)

  1 passing (2s)_

**Comment by JamesANZ** [comment]
> Thanks for that.
> Now, I am getting the message below, but no balance object.
> 
> _λ npm run test
> 
> > balances-rpc-dot@1.0.0 test C:\Users\atale\Documents\Gits\balances-rpc-dot
> > mocha --exit --recursive
> 
> AccountInfo functionality
> √ should be able to get a native balances object (1492ms)
> 
> 1 passing (2s)_

Yes, to clarify this runs a test to check that the object you get back is a balance object, if you wanna see what's inside the object you can console log it:

` it("should be able to get a native balances object", async () => {
        const accountNativeBalances = await this.accountInfo.getAccountInfo();
        console.log(accountNativeBalances); // Add this line in
        ....
`

sample output: 

`{
  nonce: 219,
  index: 1,
  freeBalance: '0x038731bdc3e76bf8',
  locked: 0,
  reserved: 1002050000000
}`

Thanks for reporting this issue
