### ISSUE TITLE
freeBalance value in hex-encoded

### ISSUE THREAD

**Issue by anaelleltd** [James-Sangalli/balances-rpc-dot#3]
This is the balance object I get on the console:

![SI_errorfreebalance](https://user-images.githubusercontent.com/44770354/130030130-71ec9dba-c5d5-4435-a092-d872993d5787.JPG)

I can't figure out how to get the freeBalance as a number, because the .ToNumber() method doesn't work for this type.

**Comment by JamesANZ** [comment]
Hi @anaelleltd, the balance is simply a hex encoded string, I am not sure why they don't also do that for the reserved balance.

To convert it to a decimal integer you can use `parseInt(hexString, 16)`
